### ISSUE TITLE
Memory leak in AnyEvent::Gearman::Client

### ISSUE THREAD

**Issue by athomason** [typester/anyevent-gearman-perl#1]
The client module leaks memory aggressively for me on Perl 5.14.0, Debian squeeze. For example, with a trivial client (https://gist.github.com/982072#file_client_anyevent.pl) and trivial worker (https://gist.github.com/982072#file_worker.pl), the client process rss sizes grows by 56,496kB after 10,000 jobs.

By comparison, a Gearman::Client::Async implementation of the same client does not leak (https://gist.github.com/982072#file_client_danga.pl).

The results are the same with the EV and Perl event backends. To test if AnyEvent itself was a problem, I also tested a mutant client that uses Gearman::Client::Async with AnyEvent instead of Danga::Socket (https://gist.github.com/982072#file_client_mutant.pl). It did not leak, suggesting an issue with AnyEvent::Gearman::Client.

Dumping the AnyEvent::Gearman::Client object with Data::Dumper after the leak does not reveal any obvious issue.

**Comment by melo** [comment]
I'll look at this Saturday.

Thanks for the report.

**Comment by athomason** [comment]
I instrumented the test case with Devel::Events::Objects and found nothing (https://gist.github.com/985867), so blessed objects aren't a clear culprit.

**Comment by athomason** [comment]
This appears to be cured by fixing the missing call to $on_complete->() in AnyEvent::Gearman::Client::Connection::add_task. Pull request sent.

**Comment by melo** [comment]
Hi,

sorry I haven't done this yet, swamped at work. I should be able to
cut a release tonight.

Thanks for the detective work.

On Mon, May 23, 2011 at 10:35 PM, athomason
reply@reply.github.com
wrote:

> This appears to be cured by fixing the missing call to $on_complete->() in AnyEvent::Gearman::Client::Connection::add_task. Pull request sent.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/typester/anyevent-gearman-perl/issues/1#comment_1224471

## 

Pedro Melo
http://www.simplicidade.org/
xmpp:melo@simplicidade.org
mailto:melo@simplicidade.org

**Comment by bluet** [comment]
I'm facing memory leak problem on my project with AnyEvent::Gearman::Client (CPAN version 0.09).
Hope new version with the patch can be uploaded to CPAN soon.
